# Generated by Django 5.2.2 on 2025-06-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpaciente',
            name='codigo_acceso',
        ),
    ]
