# Generated by Django 5.2.2 on 2025-06-12 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.FloatField(help_text='Peso total en kilogramos')),
                ('kg_grasa', models.FloatField(help_text='Kilogramos de grasa corporal')),
                ('kg_proteinas', models.FloatField(help_text='Kilogramos de proteína corporal')),
                ('kg_minerales', models.FloatField(help_text='Kilogramos de minerales')),
                ('litros_agua', models.FloatField(help_text='Litros de agua corporal')),
                ('carbohidratos_g', models.FloatField(blank=True, help_text='Carbohidratos recomendados en gramos', null=True)),
                ('proteinas_g', models.FloatField(blank=True, help_text='Proteínas recomendadas en gramos', null=True)),
                ('grasas_g', models.FloatField(blank=True, help_text='Grasas recomendadas en gramos', null=True)),
                ('calorias_totales', models.IntegerField(blank=True, help_text='Calorías totales recomendadas', null=True)),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones nutricionales específicas', null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales del nutricionista')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'db_table': 'valoraciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
