# Generated by Django 5.2.2 on 2025-06-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='tabla_equivalencias',
            field=models.TextField(blank=True, help_text='Tabla de equivalencias funcionales de alimentos', null=True),
        ),
    ]
